/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const GameGameIdLobbyLazyImport = createFileRoute('/game/$gameId/lobby')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameGameIdLobbyLazyRoute = GameGameIdLobbyLazyImport.update({
  path: '/game/$gameId/lobby',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/game.$gameId.lobby.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId/lobby': {
      id: '/game/$gameId/lobby'
      path: '/game/$gameId/lobby'
      fullPath: '/game/$gameId/lobby'
      preLoaderRoute: typeof GameGameIdLobbyLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  GameGameIdLobbyLazyRoute,
})

/* prettier-ignore-end */
