/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const GameGameIdRoomLazyImport = createFileRoute('/game/$gameId/room')()
const GameGameIdLobbyLazyImport = createFileRoute('/game/$gameId/lobby')()

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const GameGameIdRoomLazyRoute = GameGameIdRoomLazyImport.update({
  path: '/game/$gameId/room',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/game.$gameId.room.lazy').then((d) => d.Route),
)

const GameGameIdLobbyLazyRoute = GameGameIdLobbyLazyImport.update({
  path: '/game/$gameId/lobby',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/game.$gameId.lobby.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId/lobby': {
      id: '/game/$gameId/lobby'
      path: '/game/$gameId/lobby'
      fullPath: '/game/$gameId/lobby'
      preLoaderRoute: typeof GameGameIdLobbyLazyImport
      parentRoute: typeof rootRoute
    }
    '/game/$gameId/room': {
      id: '/game/$gameId/room'
      path: '/game/$gameId/room'
      fullPath: '/game/$gameId/room'
      preLoaderRoute: typeof GameGameIdRoomLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  GameGameIdLobbyLazyRoute,
  GameGameIdRoomLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game/$gameId/lobby",
        "/game/$gameId/room"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game/$gameId/lobby": {
      "filePath": "game.$gameId.lobby.lazy.tsx"
    },
    "/game/$gameId/room": {
      "filePath": "game.$gameId.room.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
